matrix:
  include:
    - env: ML_VERSION=8.0-7
    - env: ML_VERSION=9.0-1.1
    - env: ML_VERSION=9.0-2
    - env: ML_VERSION=9.0-3

dist: trusty
sudo: required
services:
  - docker

before_install:
 - ./.travis/download.sh

script:
  - docker run marklogiccommunity/marklogic-datahub:${ML_VERSION}
